import React from 'react';

export default class Dashboard extends React.Component {
  render(){
    return(
      <div>
        <div>
          FODA-SE
        </div>
        <div>
          FODA-SE
        </div>
        <div>
          FODA-SE
        </div>
        <div>
          FODA-SE
        </div>
        <div>
          FODA-SE
        </div>
        <div>
          FODA-SE
        </div>
        <div>
          FODA-SE
        </div>
        <div>
          FODA-SE
        </div>
        <div>
          FODA-SE
        </div>
        <div>
          FODA-SE
        </div>
        <div>
          FODA-SE
        </div>
        <div>
          FODA-SE
        </div>
        <div>
          FODA-SE
        </div>
      </div>
    )
  }
}
